version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/kphp-developers"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "VKCOM/vk-sec"
      - "VKCOM/kphp-developers"
