Deploy package:
  only:
    - tags
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "https://gitlab.apark.pro/taxi/v4/projects/$CI_PROJECT_ID/packages/composer"'
